[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml' 

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'
hook_add = '''
let g:goimports = 1
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'javascriptreact', 'typescriptreact']

[[plugins]] # typescript syntax
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact', 'javascript']
if = "!has('nvim')"

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['typescript', 'typescriptreact', 'javascript']

[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['typescriptreact', 'javascriptreact']
